# Generated by Django 4.2.9 on 2024-02-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_alter_formfield_page_alter_formpage_extra_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
