# Generated by Django 4.2.9 on 2024-02-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_ad_openinghours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
