# Generated by Django 4.2.9 on 2024-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='day',
            new_name='dayF',
        ),
        migrations.AddField(
            model_name='ad',
            name='dayT',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True),
        ),
    ]
