# Generated by Django 4.2.9 on 2024-02-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0010_rename_day_ad_dayf_ad_dayt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='dayF',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='dayT',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True, verbose_name='To'),
        ),
    ]
