# Generated by Django 4.2.9 on 2024-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0014_formpage_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='show_advertisement',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
