# Generated by Django 4.2.9 on 2024-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0015_formpage_show_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='advertisement_header',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
