# Generated by Django 5.0 on 2023-12-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_flexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexPage',
        ),
    ]
