# Generated by Django 5.0 on 2023-12-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_wiggle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wiggle',
        ),
    ]
