# Generated by Django 5.0 on 2023-12-16 22:50

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_wiggle'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiggle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('carousel', wagtail.fields.StreamField([('carousel', wagtail.blocks.StructBlock([('banner_image', wagtail.images.blocks.ImageChooserBlock()), ('banner_header', wagtail.blocks.CharBlock()), ('banner_subheader', wagtail.blocks.CharBlock(required=False)), ('page_redirect', wagtail.blocks.PageChooserBlock(required=False))]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
