# Generated by Django 5.0 on 2024-01-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_wiggle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexPage',
        ),
    ]
