# Generated by Django 5.0 on 2024-01-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_blogpage_blogpagerelatedlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wiggle',
        ),
    ]
