# Generated by Django 5.0 on 2024-01-20 17:23

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_wiggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiggle',
            name='components',
            field=wagtail.fields.StreamField([('banner_carousel', wagtail.blocks.StructBlock([('purpose', wagtail.blocks.CharBlock(default='Main Page Banner')), ('slides', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('slide_image', wagtail.images.blocks.ImageChooserBlock()), ('slide_header', wagtail.blocks.CharBlock()), ('slide_subheader', wagtail.blocks.CharBlock()), ('page_redirect', wagtail.blocks.PageChooserBlock(required=False))])))])), ('about_us', wagtail.blocks.StructBlock([('purpose', wagtail.blocks.CharBlock(default='About Us', editable=False)), ('img1', wagtail.images.blocks.ImageChooserBlock()), ('img2', wagtail.images.blocks.ImageChooserBlock()), ('pre_header', wagtail.blocks.CharBlock()), ('main_header', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.TextBlock()), ('page_redirect', wagtail.blocks.PageChooserBlock(required=False))]))], use_json_field=True),
        ),
    ]
