# Generated by Django 5.0 on 2024-01-22 20:54

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiggle',
            name='components',
            field=wagtail.fields.StreamField([('banner_carousel', wagtail.blocks.StructBlock([('purpose', wagtail.blocks.CharBlock(default='Main Page Banner')), ('slides', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('slide_header', wagtail.blocks.CharBlock()), ('slide_subheader', wagtail.blocks.CharBlock()), ('slide_image', wagtail.images.blocks.ImageChooserBlock()), ('page_redirect', wagtail.blocks.PageChooserBlock(required=False))])))])), ('about_us', wagtail.blocks.StructBlock([('purpose', wagtail.blocks.CharBlock(default='About Us')), ('img1', wagtail.images.blocks.ImageChooserBlock()), ('img2', wagtail.images.blocks.ImageChooserBlock(required=False)), ('pre_header', wagtail.blocks.CharBlock()), ('main_header', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.TextBlock()), ('page_redirect', wagtail.blocks.PageChooserBlock(required=False))])), ('page_intro', wagtail.blocks.BooleanBlock(default=False)), ('blog_section', wagtail.blocks.StructBlock([('purpose', wagtail.blocks.CharBlock(default='Section for Blog cards')), ('pre_header', wagtail.blocks.CharBlock(max_length=20)), ('header', wagtail.blocks.CharBlock(max_length=50)), ('sub_header', wagtail.blocks.CharBlock())]))], use_json_field=True),
        ),
    ]
