# Generated by Django 4.2.9 on 2024-02-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
