# Generated by Django 4.2.9 on 2024-02-07 22:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('pages', '0020_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_description', models.CharField(blank=True, max_length=70)),
                ('components', wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image for the paragraph', required=False)), ('iamge_position', wagtail.blocks.ChoiceBlock(choices=[('C', 'Full Central'), ('L', 'Left Aligned'), ('R', 'Right Aligned')], help_text='Tells where the image should be positioned', required=False)), ('body', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True)),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
