# Generated by Django 4.2.9 on 2024-02-07 22:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='component',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image for the paragraph', required=False)), ('iamge_position', wagtail.blocks.ChoiceBlock(choices=[('C', 'Full Central'), ('L', 'Left Aligned'), ('R', 'Right Aligned')], help_text='Tells where the image should be positioned', required=False)), ('body', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=True),
        ),
    ]
