# Generated by Django 4.2.9 on 2024-02-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_blog_component'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
