# Generated by Django 4.2.9 on 2024-02-25 14:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_delete_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='component',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image for the paragraph', required=False)), ('image_position', wagtail.blocks.ChoiceBlock(choices=[('L', 'Left Aligned'), ('R', 'Right Aligned')], help_text='Image position (default Center)', required=False)), ('body', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=True),
        ),
    ]
