# Generated by Django 4.2.9 on 2024-02-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_blog_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.CharField(blank=True),
        ),
    ]
