# Generated by Django 4.2.9 on 2024-02-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_blog_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='advertisement_header',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_list_header',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
