# Generated by Django 4.2.9 on 2024-03-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_blog_advertisement_header_blog_blog_list_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show_advertisement',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
