# Generated by Django 4.2.9 on 2024-03-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_blog_show_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='advertisement_header',
            field=models.CharField(blank=True, default='Advertisement', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_list_header',
            field=models.CharField(blank=True, default='Other Blogs', max_length=20, null=True),
        ),
    ]
