# Generated by Django 4.2.9 on 2024-03-10 21:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_wiggle_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='component',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image for the paragraph', required=False)), ('image_position', wagtail.blocks.ChoiceBlock(choices=[('L', 'Left Aligned'), ('R', 'Right Aligned')], help_text='Image position (default Center)', required=False)), ('body', wagtail.blocks.RichTextBlock())])), ('fact_band', wagtail.blocks.StructBlock([('facts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.IntegerBlock()), ('fact', wagtail.blocks.CharBlock(max_length=50))])))]))], blank=True, use_json_field=True),
        ),
    ]
