# Generated by Django 4.2.9 on 2024-03-10 22:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_blog_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiggle',
            name='components',
            field=wagtail.fields.StreamField([('banner_carousel', wagtail.blocks.StructBlock([('slides', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('slide_header', wagtail.blocks.CharBlock()), ('slide_subheader', wagtail.blocks.CharBlock()), ('slide_image', wagtail.images.blocks.ImageChooserBlock())])))])), ('about_us', wagtail.blocks.StructBlock([('img1', wagtail.images.blocks.ImageChooserBlock()), ('img2', wagtail.images.blocks.ImageChooserBlock(required=False)), ('pre_header', wagtail.blocks.CharBlock()), ('main_header', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.TextBlock()), ('page_redirect', wagtail.blocks.PageChooserBlock(required=False))])), ('page_intro', wagtail.blocks.BooleanBlock(default=True)), ('blog_section', wagtail.blocks.StructBlock([('pre_header', wagtail.blocks.CharBlock()), ('header', wagtail.blocks.CharBlock()), ('sub_header', wagtail.blocks.CharBlock())])), ('team_section', wagtail.blocks.StructBlock([('pre_header', wagtail.blocks.CharBlock()), ('header', wagtail.blocks.CharBlock())])), ('fact_band', wagtail.blocks.StructBlock([('facts', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.IntegerBlock()), ('fact', wagtail.blocks.CharBlock(max_length=50))])))]))], use_json_field=True),
        ),
    ]
