# Generated by Django 4.2.9 on 2024-03-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_wiggle_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='advertisement_header',
        ),
    ]
