# Generated by Django 4.2.9 on 2024-03-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.URLField()),
            ],
        ),
    ]
