# Generated by Django 4.2.9 on 2024-03-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammembers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
