# Generated by Django 4.2.9 on 2024-03-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('teammembers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='display_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
