# Generated by Django 5.0 on 2023-12-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navitem',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='pagelist',
            name='nav_item',
        ),
        migrations.RemoveField(
            model_name='pagelist',
            name='link',
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
        migrations.DeleteModel(
            name='PageList',
        ),
    ]
