# Generated by Django 4.2.9 on 2024-01-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_navbar2_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navtab',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='pagelist',
            name='nav_tab',
        ),
        migrations.RemoveField(
            model_name='pagelist',
            name='page_link',
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.DeleteModel(
            name='NavTab',
        ),
        migrations.DeleteModel(
            name='PageList',
        ),
    ]
