# Generated by Django 4.2.9 on 2024-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_alter_sample_unique_together_remove_sample_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelist',
            name='external_resource',
            field=models.URLField(blank=True, null=True),
        ),
    ]
