# Generated by Django 4.2.9 on 2024-02-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0013_navigationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
    ]
