# Generated by Django 4.2.9 on 2024-03-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('menus', '0014_delete_navigationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='name1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
