# Generated by Django 4.2.9 on 2024-03-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0016_pagelist_resource_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelist',
            name='external_resource',
            field=models.URLField(blank=True, help_text='URL', null=True),
        ),
        migrations.AlterField(
            model_name='pagelist',
            name='resource_label',
            field=models.CharField(default='unlabelled', help_text='Link Short Name', max_length=15),
        ),
    ]
