# Generated by Django 4.2.9 on 2024-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0018_alter_pagelist_resource_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelist',
            name='resource_label',
            field=models.CharField(default='external', help_text='Link Short Name', max_length=15),
        ),
    ]
