# Generated by Django 4.2.9 on 2024-04-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0019_alter_pagelist_resource_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navtab',
            name='nav_title',
            field=models.CharField(blank=True, help_text='Ignore if single page / external link', max_length=20, null=True),
        ),
    ]
